language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: W1imrmyVXU0luFRCEY9ALwsEbIRLXy5TAH1qMttRIEnJpBCnI2zFVRAFuEE0WsLZTluOEd3iVoWGd8ymBvjfWSIx+PJ4lrQu1/DFoI6RHUh1+0Ru9uwmYVY2QZljnqjJFzbYHrR0rTTSjizun1mc8hq3bwewWaA6B/EGddpB2UYJeN+RNiRnYhmCnvcn4CyjpKbWf5993Bc4aMZhgHzo/yqz1tXFtgS4I44QNh5H/sOx4cqhmrOxcYJ6EZAm6Br47QrW0A06wSrTuRjPZL3QF9o9rGGjawk5HDxLlOqL+DHqiO4ObajU9YI/ZSNxnyjDFOHyVt3akN9ZTiNookw6q39m88bPJlZ/C00gJWn17ikLK41axzWFR0Te25LjSbHK8514gT8QWUf1iO6qX/BKo/o6r2sz3w3redDAbfDcsF0YcXVsjY6uaZtMf1KpmF3RVfCWbzCyUUGCYBAp2vfTzJkKuYBhtD4wbFpdAhIj9WRd1Ia23MhD5r+6/tAaCaSaOnupJlE50rnwar6JyvwTz6764J85B3Ydmcp/agSzfvwbwcecETv6dtq/qNqSxfbDaYW7M/bFmLFRz82ECaGQGIoBsXeYppPhCTO53AwIsIJ58GGMhSkxhLyUr6HTkupzjk5pmj5/9c+41MaJdUbW0nI9dG2UJQI/4wAXOiCzllc=
  app: brewfinder-untermeyer
  skip_cleanup: true
