language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: yPuqg9bgcDvuGicLlFSikDw9FsxDFyYFzUJneS+2KRAdKou5cjaSC6sjSlFTgpKjuAHTBXpF4WMPL2A6/+IAvFeWqLCZPg5LOQ0ItZUl9C7VFEJl0/6IgQgYbkSqO/8gzQBD+WTzNOpgXswgRP2WdVjqaFH9+gOKpG3NXKqIxhcmpUAXOCP30kaiPu1OPMmZouJZWVw8rBTkmhxhOdri75FCJl7jcLWT2qvmUJdZhkAqc4mNgRiqfvVZ1yR3baLUzNxZfcNPu5iIspPzWVG7+qcnhFeZbuQ9lF5VDN7mtWSmgRY2RRB7l2XCGCd36TNxFvN6Ew7SI+ne7w3OA4Mn4rmbCHdqAOTa5XjGiiegwUh3lSdh0n2TbyWbSlS/6pBYZFAEqr0hK6ghv5NCyiy1yQ6lzmeC9P4gzbGQyx7RcRYnQGZW3ahCqe4qE1NMKzfUvzqV5EgC+uG4oOsM+D2RC8HpCZFB9sRinnFV1aUN5f1jmFAdRSQqdmSk+GI6eHilqzcfmFgX1l9bD3peZ5bKslKExraKMd9uy2nj4wFChikh0r4lbWr3YXw1Mi/ZaerUi1kxSavHRIG/NCoCpC/iXLjVrs2f2t3VG7M/geYWYcsnbUvptcdnFilyX+VpTMT/wSdEhxvriNhaFV5095GIUefgU9S/egot6R9S5H66XyA=
  app: brewfinder-untermeyer
  skip_cleanup: true
