language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: j5poGOD+YyrcQcta4xJvSHG0BrDp3Ay7aQw3IYxceOPPJz1z2dBUg+P5cN/Hr7pwFW4piJPaad8mR48tpMfQqmWDBsB0exOXX8rBWQsZC8ns6ohjy1kBoTOgh+xtTU3HJ2QVYzUJ/21I5RFdJw4p0n9LJPiY1jbp//GmG8MrewDO1ReG2V1bYuWLVi8lFuNLzrNx4KyK8TLqHmLY/0lZ7DCCtfwFnIFWYq3VztcP0MZF2NFwjOfhZyUkhPGDeuKZe90H+VDPP/Fk2nHvy6luLWn078jbulxOtBQx+x5ibt0j9COw7C2IolFbkFtL85VQOPuQvAQ41FYLhZp3TIwJn/Sj+pl+roGkp/AQzzBKCnSWQEE1pS00n//ljV+++nqRx0vfxl1VNNu0tszZNNYsYKTiGFYsYfym/MrMhBaPDmBmFSKoxS8rr3CLeEEpm79mggqWNgTo4EPEBpNRLuRMmIyuvsXxzX4KW50ZobL8ovT7e6kyXwP0hAPblRd3TjoCe0rLKpepAlduHTNx4INii8eLlqsjaMraRS5SUes+rJ3yXqVu/uKK+FnKQIo+fFfcBhtKrEKbVLKp9d/iNk7kLnGvBKVKlggFlZ6X5XUi1DFSlNoTpj9M6cBBR500A9Zc4yxBTekhNKLQ0/brT3oOgjucvlznN7m7eLRY8IfBuwQ=
  app: brewfinder-untermeyer
  skip_cleanup: true
