language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ECz0xvSQWVnSFCkNjz33++e9L+xxswzqmOrrLSqdSEErwoSe81UCzIgR7bVwv4ZjkTLiZzIcbf76fpwgypy/hsAjih7GAbccGaWH2GXRO/Lt3/pHxqmBVNyu+1IYsHiHG00UO9ZfMn/6EqzSNt4bOpZ8S/I7QYpknRnqiMiTItL8vyG2D90tRUOW7uClFq3r54Ts/37/3dvasGatnxc7m0aLqnPrC+oefyoQeadWqx/3zxZAbm6UssmCH7WfZbN2uJbQInfxQYLuu1flieIDdeBQ0v8UFkUP+jDiT1R6CHFMnNk8cLXMHTvQZxUf0rN77maL99WTy6ZWggY8MetgGKjOIZLgueTLpOV7OYnmKiEidBfEAt4uPsnk8UnVt5EZTAfw/2pD6PG/Ej0qEZ1i3iuzvS6aH6Tv/PID9LcryWnCu4YV9SqtU36rvEDab20Xaqx457PpJCSEbCIhnJ/vNhQLcgNBtz8qqWze4W0z8IRM0+b3j5P1riuAHCaqM1ToG0YFcTAhR6T9RCu4/HGhMz0zOFmBs1ZRCXoo8ax6Rp31tGwZdWItt1D+LwkZLRe27f9WaLhGkCKqQVNt6GKKUtjEn1gdt6eJEEeRlNRHn8jlAZw2SH36eb93A/cshllTblpkiAAwpxa9scn0DRAB7EqTvD4I4itSm+HQo4TfSjI=
  app: brewfinder-untermeyer
  skip_cleanup: true
