language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: m3zOgDWKkVI0kBNcccvvPD+XTfR+2TlLGiu6tKECgA+BUZS1MIU146ITOq/wA2uExPm0R5Zb7+fxiBUKKyIl4hBdGRwnAT7lNqvU4JJsEBktRO5pNWGL5CgEL+3oIa5A3JxaYpFRvKSU7AmCbVKzCcRSTpI2dBFELhjUwyx90yprcjjkzJYXOn5pRkFWjWtyiUNVMI6RSd3RvrMUWqU0/fTKCrdS7sxrmvFtXJmK3ZbIOWQ0wu796c2XGTkA9z8KzAPWStg4vukQJshPzRPr+sgRDOx0jii3Megc5eoUtxshHkBUysXJ4xzp2f4Vs57lg0ILjeUhHLXxVltm7oFngB2yD5ZztnsfOXBxMzxMubuL1Uxnt6raMSnGYxz64Tm0hz4VICl0xJMgJF2JY3mdYskzHpfoASdiyLShkggTrh4t57u4fbItXkuWmbp3lKTUtSBlPIpIupiSXNeTJgfH3wguN94JK429/5HPOWElvXCubDufwy8FTWn+edyEUQ9TKQfr+Y8H+58KoDdcgT7JQnReGZI9x861jpxp05Ltr/1gnKD7mSde2+Mzs1/tmmFP7jjmi5z40253FFRLMWHhHpauMKLQzbp+HXaiCAK2ATLoFOBhWRgbqXUhcL+iIYJtvVY8hnsXybcQzTD6wGH1ROO0rQmazBMO0LN4DUtnP9Q=
  app: brewfinder-untermeyer
  skip_cleanup: true
